### PR TITLE
Add Hello Bar script

### PR DESCRIPTION
**Pull request by katiecrane**
### What does this PR do?

This PR adds the Hello Bar script to our site! It can only show up on prod, but I'm seeing this message locally so I think I did it right:
image

### Any background context you want to provide?

We'll be testing this on prod on low traffic pages. For additional context, here is the PR for when we added this before (in Ashes!): https://github.com/DoSomething/phoenix/pull/7519

### What are the relevant tickets/cards?

Refs [Pivotal ID #169608418](https://www.pivotaltracker.com/story/show/169608418)

### CODE REVIEW

**Comment by DFurnes** [comment]
> I feeeeel like we discussed this in Planning but I can't recall -- did we want to add a QA HelloBar to be able to test things out? (Not that that would be a blocker for this since that'd also be configured via HelloBar, right?)

That feels like it could be helpful!

**Comment by katiecrane** [comment]
@DFurnes @mendelB we'd need a separate snippet for each environment. The one we have now is locked to prod and can't be used on QA. As far as I can tell, in Ashes we only ever had on snippet? Should we have two?

**Comment by DFurnes** [comment]
Oh, that's frustrating. If we've never needed it in the past, it's probably not worth the hassle then.

**Comment by katiecrane** [comment]
@DFurnes right?? Seems like we should be able to whitelist it, but alas! Low traffic pages on prod to test it is

**Comment by mendelB** [comment]
meme

**Comment by katiecrane** [comment]
hahaha @mendelB you know I'd only agree to this if we had no choice!!

**Comment by mendelB** [comment]
> hahaha @mendelB you know I'd only agree to this if we had no choice!!

lol but that adrenaline rush is to die for. I only test on _QA_ when they twist my arm.

**Comment by katiecrane** [comment]
this is @mendelB:

free_solo_

**Pull request merged**
