### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by DFurnes**
### What's this PR do?

This pull request updates PHP & JavaScript dependencies, including [Laravel 6.20.11](https://blog.laravel.com/security-laravel-62011-7302-8221-released), [contentful-management 7.x](https://github.com/contentful/contentful-management.js/releases) (allowing us to clear up a low-severity, for our use, Axios issue), and [Cypress 6.x](https://docs.cypress.io/guides/references/changelog.html#6-2-1) (which gets us some fresh network mocking tools).

### How should this be reviewed?

I've run through core flows & ran our test suites and everything looks a-okay to me!

### Any background context you want to provide?

🔏 

### Relevant tickets

References [Pivotal #176481917](https://www.pivotaltracker.com/story/show/176481917).

### Checklist

- [ ] This PR has been added to the relevant Pivotal card.
- [ ] Documentation added for new features/changed endpoints.
- [ ] Added screenshots of front-end changes on small, medium, and large screens.
- [ ] Added appropriate feature/unit tests.

### CODE REVIEW

**Comment by DFurnes** [comment]
This [minor release](https://github.com/lcobucci/jwt/releases/tag/3.4.0) introduces a ton of deprecations for this library's upcoming 4.x release, which in turn trigger `E_USER_DEPRECATED` errors. This would force us to address the API changes now (a lot of breaking changes!) or adjust our overall error reporting (not great).

Since there aren't any security related fixes in the `3.4.*` releases, I'm pinning `3.3.*` in 19d8479 to avoid a ton of re-work. Once we've got our other Laravel applications unified, we can replace Gateway's middleware/test helpers with plain [oauth2-server](https://github.com/thephpleague/oauth2-server).

**Comment by DFurnes** [comment]
Alright, somehow I ended up with other missing dependencies that should have been installed? Re-running a fresh `composer install` fixed the issue (after dealing with this unrelated and apparently very spooky [Vagrant/Composer issue](https://git.io/JtJKo))... 🤞

**Review by aaronschachter — APPROVED** [review]
I pulled this branch down locally to install and test. everything looks good, except I also get the same failed Cypress test for Campaign Signups: "Visits a campaign page from a scholarship partner, as an authenticated user"

**Comment by DFurnes** [comment]
Yeah, hmm. I'd been hoping that was one of those flaky test failures when I saw the ❌... didn't run into it when I ran Cypress originally but I'm seeing it now. Gonna dig in and see what's gone wrong there!

**Comment by DFurnes** [comment]
Ok, should be back in business. Cypress 6.0 throws an error if you [use an assertion on a non-existent element](https://docs.cypress.io/guides/references/migration-guide.html#Non-existent-element-assertions) - so while we used to be able to say "there should be a button inside this element" before, now it'll fail because while there really _isn't_ a button there, that's because the container only renders if unaffiliated.

**Review by aaronschachter — APPROVED** [review]
Great catch! 🎣

**Pull request merged**
