### PR TITLE
Adds optional CivicEngine Voting Widget embed to ContentBlock

### PR DESCRIPTION
**Pull request by aaronschachter**
### What's this PR do?

This pull request adds support to embed a [CivicEngine Voting Widget](https://developers.civicengine.com/docs/widget/) in a `ContentBlock` by setting a `footerType` property to `VotingWidgetBlock` in the `additionalContent` JSON field. 

This voting widget will only be used for voter registration -- it seemed a bit overkill to create a new content type in Contentful and go through the workflow of adding it to GraphQL and our ContentfulEntryLoader/ContentfulEntry components. We have a similar feature request for this sprint that @lindsayrmaher is working on, for a "Get Out The Vote" block type that will only be used for a one-off campaign -- that could be another `footerType` value supported (e.g. `footerType: 'GetOutTheVoteBlock'`) 

I'll add more info about the `VotingWidgetBlock` to documentation in a follow-up PR if this all looks 👍 

Mobile:
Screen Shot 2020-09-18 at 2 06 39 PM

Desktop:
Screen Shot 2020-09-18 at 2 06 27 PM

### How should this be reviewed?

👀 

### Any background context you want to provide?

I followed the "Silver Level" instructions for embedding the Voting Widget, which supports auto-resizing, and sending along a UTM parameter. When I'm logged into the DS site in Chrome, the widget will fail to load locally. There's a console error 

> DevTools failed to load SourceMap: Could not parse content for https://app.[removed].civicengine.com/iframeResizer.map: Unexpected token < in JSON at position 0

It works correctly incognito in Chrome locally, as well as Safari (anonymous, and authenticated). I sent an email to the CivicEngine support to ask about this issue, as it seems to be on their end, and related to https://github.com/davidjbradshaw/iframe-resizer/issues/136.

### Relevant tickets

References [Pivotal #174199686](https://www.pivotaltracker.com/story/show/174199686).

### Checklist

- [x] This PR has been added to the relevant Pivotal card.
- [x] Documentation added for new features/changed endpoints.
- [x] Added screenshots of front-end changes on small, medium, and large screens.
- [ ] Added appropriate feature/unit tests.

### CODE REVIEW

**Comment by aaronschachter** [comment]
Testing on the review app with the `ContentBlock` I created on dev: https://dosomething-phoenix-de-pr-2358.herokuapp.com/us/blocks/772nliHy7544iwCIT78x8

And see a `SyntaxError: Unexpected token '<'` in the console, which is the same error I mention in the description. I'm eager to hear back to see if this an issue on the CivicEngine side (but also getting a bit skeptical about how much of a win this is if the widget continues to be troublesome...)

**Comment by aaronschachter** [comment]
Just kidding! I forgot to set the new `DS_VOTING_WIDGET_SRC_URL` config variable -- the [review app](https://dosomething-phoenix-de-pr-2358.herokuapp.com/us/blocks/772nliHy7544iwCIT78x8) now works.

**Review by katiecrane — APPROVED** [review]
looks great to me, thanks for updating .env.example and some of the docs in here!

**Comment by aaronschachter** [comment]
Thanks for reviewing @katiecrane ! I've tested the review app in Safari on my iPhone and the widget won't load. For now, I'm going to merge this so @lindsayrmaher can add support to display the `GetOutTheVoteBlock` in the footer of a `ContentBlock`, and follow up in Slack about next steps for getting this widget working.

**Pull request merged**
