### PR TITLE
Restructuring the Phoenix Docs.

### PR DESCRIPTION
**Pull request by weerd**
### What does this PR do?

This PR restructures the Phoenix Documentation now that all of the content publishing content lives in a separate document for editors. With that in mind we can make these docs more technical and hopefully aim to update them more easily as we update code and add features to Phoenix! 🎉 🤓 

See the following, for a good example page to see the potential for where we could take these docs:
<https://dosomething.gitbook.io/phoenix-documentation/v/doc-restructuring-the-phoenix-documentation/development/content-types/metadata>

### Any background context you want to provide?

Let's Improve The Docs™

### What are the relevant tickets/cards?

Refs [Pivotal ID #162742818](https://www.pivotaltracker.com/story/show/162742818)

### CODE REVIEW

**Comment by weerd** [comment]
There are very likely some broken links in content; ignore these for now. Once new structure is set, we'll do a pass to update and add new info!

**Comment by weerd** [comment]
Decided to also remove (for the most part) "Overview" pages for sections, which in prior docs acted as a mini table of contents for the pages in a section. No one used these, and were mostly just annoying to remember to update the list of links, so they got the chopping block. 🔪

**Comment by weerd** [comment]
Also thought it'd be nice to add a [template for content types](https://github.com/DoSomething/phoenix-next/pull/1371/commits/6f3d1967cd1aacffee7735270d5bd9258ce482a2) which could be nice to follow. If the template idea works out, we could do it for other sections too. Just copy, rename and add info for the new item.

**Comment by mendelB** [comment]
> Also thought it'd be nice to add a [template for content types](https://github.com/DoSomething/phoenix-next/pull/1371/commits/6f3d1967cd1aacffee7735270d5bd9258ce482a2) which could be nice to follow. If the template idea works out, we could do it for other sections too. Just copy, rename and add info for the new item.

I thought this was a nice touch!

**Pull request merged**
