### PR TITLE
Paginated Campaign Gallery - New Algolia Filters

### PR DESCRIPTION
**Pull request by mendelB**
### What's this PR do?

This pull request follows up on #2456 to add the new filters to the `searchCampaigns` Algolia query in the `PaginatedCampaignGallery`. 

I also took the opportunity to retire the `DS_ENABLE_HIDE_CAMPAIGNS` env variable/feature flag since we've been using it for a while with success.

### How should this be reviewed?
👀 

### Any background context you want to provide?
Our Algolia campaigns search is still hidden behind a feature flag, so this won't affect the production website quite yet.

### Relevant tickets

References [Pivotal #175358477](https://www.pivotaltracker.com/story/show/175358477).

### Checklist

- [x] This PR has been added to the relevant Pivotal card.
- [x] Documentation added for new features/changed endpoints.
- [x] Added appropriate feature/unit tests.

### CODE REVIEW

**Review by aaronschachter — COMMENTED** [review]
This code looks good, but it also looks like some tests might need to be updated?

**Comment by mendelB** [comment]
> This code looks good, but it also looks like some tests might need to be updated?

Hrmm not sure why these are failing it's all passing locally 🤔. Taking a look!

**Comment by mendelB** [comment]
Aha! I think we're just missing the `npm run schema:fetch` https://github.com/DoSomething/phoenix-next/pull/2456/commits/28325a15392a4ddd73a03e61f74625c2aec95b73 pending approval in #2456

**Comment by mendelB** [comment]
> Aha! I think we're just missing the `npm run schema:fetch` [28325a1](https://github.com/DoSomething/phoenix-next/commit/28325a15392a4ddd73a03e61f74625c2aec95b73) pending approval in #2456

Additionally, by removing the feature flag to 'hide campaigns', a test was failing since GraphQL was stubbing `groupTypeId`s for the results, and thus the expected count was off -- fixed in https://github.com/DoSomething/phoenix-next/pull/2457/commits/c8f9c0aa007daca65455b9a4ad93878642cb9d84!

**Review by aaronschachter — APPROVED** [review]

**Pull request merged**
