### PR TITLE
WIP: Support blocks in pitch page sidebar.

### PR DESCRIPTION
**Pull request by DFurnes**
### What does this PR do?
This pull request adds support for blocks in the pitch page sidebar. Once we update validation rules in Contentful, editors should be able to place any (allowed) block(s) in this field & they'll render real nice:

screen shot 2018-11-09 at 2 32 54 pm

### Any background context you want to provide?
…

### What are the relevant tickets/cards?
Refs [Pivotal ID #161561026](https://www.pivotaltracker.com/story/show/161561026).

### Checklist

* [ ] Documentation added for new features/changed endpoints.
* [ ] Added appropriate feature/unit tests.
* [ ] Added screenshot to PR description of related front-end updates on **small** screens.
* [ ] Added screenshot to PR description of related front-end updates on **medium** screens.
* [ ] Added screenshot to PR description of related front-end updates on **large** screens.

### CODE REVIEW

**Comment by DFurnes** [comment]
@weerd @mendelB I've got this working with the `static` block. We'll need to add a "title" filed to the Campaign Update (Card Block) content model in order to use it here (since right now those titles are hardcoded to "Campaign Update"). Sound good to y'all?

**Comment by DFurnes** [comment]
I've added a "Card Block" content type in 58866dd, with the same fields as the existing "Campaign Update" (minus Affiliate Logo & Display Options), and with Metadata subbed in for Social Overrides.

**Comment by DFurnes** [comment]
I've added the ability to add Card Blocks to landing page sidebars in 6a19faf, and added a new distinct `CardBlock` component & transformer in 7fa129c (replacing the old `StaticBlock`). This could use some extra testing, but seems to work nicely on [#SuperStressFace's landing page, in dev](https://app.contentful.com/spaces/81iqaqpfd8fy/environments/dev/entries/4FjBdzIBQA40Mm8ywwI6IS):

screen shot 2018-11-12 at 5 23 31 pm

**Comment by DFurnes** [comment]
It's worth re-iterating that the new "Card Block" does not support the "Affiliate Logo" from the old campaign update nor the "sources" field from the old Static Block. I think both are rarely used.

**Comment by DFurnes** [comment]
We'll also probably want to revisit creating a script to transform page entries used as landing pages into the standalone Landing Page entity, since many campaigns are still configured the old way.

**Comment by weerd** [comment]
Closing for now since this PR has become stale and has numerous merge conflicts. We can always re-purpose the code and reuse if/when needed.

**Pull request closed without merging**
