### PR TITLE
Require authentication for the Alpha ReferralPage 

### PR DESCRIPTION
**Pull request by aaronschachter**
### What does this PR do?

This PR modifies the `/us/refer-friends` Alpha Referral Page ("Want free stuff?") to require authentication, and uses the logged in user's ID instead of relying on a `user_id` query parameter. With that in place, it makes sense to refactor a single `ReferralPage` component with templates instead as separate `AlphaPage` and `BetaPage` components, where only the `BetaPage` needs to query GraphQL by the `user_id` query parameter. 

There are no visible front-end changes, this is just moving around the existing code to simplify it.

### Any background context you want to provide?

 I think this is much cleaner, and also makes sense for the Alpha page to be limited to the logged-in user's ID. Will add sample URL's once review app is built.

### What are the relevant tickets/cards?

https://www.pivotaltracker.com/story/show/167602877

### Checklist

* [ ] Documentation added for new features/changed endpoints.
* [ ] Added appropriate feature/unit tests.
* [ ] Added screenshot to PR description of related front-end updates on **small** screens.
* [ ] Added screenshot to PR description of related front-end updates on **medium** screens.
* [ ] Added screenshot to PR description of related front-end updates on **large** screens.

### CODE REVIEW

**Comment by aaronschachter** [comment]
Hmm, this review app keeps returning a `Client authentication failed` error when I try to login 😢 so is the one over in #1545 - https://dosomething-phoenix-de-pr-1545.herokuapp.com/us

**Comment by weerd** [comment]
Ah, that's one of the current caveats with the review apps. Since the domains are generated based on branch ID, we can't specify a Redirect URI for OAuth flow in the `dev-oauth` client on Aurora. I think you could either edit the client for dev and add `https://dosomething-phoenix-de-pr-1545.herokuapp.com/us/next/login`, remembering to remove it after merging... or just wait to test this on dev.ds.org after merge.

Known issue, but not sure if we have a sufficient proposed solution to resolve.

**Comment by aaronschachter** [comment]
Ah yes - I'll fix the order of the import statements.

I did consider what you mention about the Alpha page no longer being able to be hyperlinked... but I think for the most part we'd always be prompting someone over email or text to share the Beta page (here's an example: https://app.goabstract.com/share/e74d31e1-2e56-49c7-a385-5bb98ab41313?collectionLayerId=13e05ce7-d3db-41a0-80ae-d688f81dd017&mode=design)

It's unlikely it'd happen but it'd also be somewhat strange to access another user's alpha page by changing the `user_id` parameter (whereas on the beta page, i could have multiple friends who are referring me to join DS)

**Comment by mendelB** [comment]
> Ah yes - I'll fix the order of the import statements.
> 
> I did consider what you mention about the Alpha page no longer being able to be hyperlinked... but I think for the most part we'd always be prompting someone over email or text to share the Beta page (here's an example: https://app.goabstract.com/share/e74d31e1-2e56-49c7-a385-5bb98ab41313?collectionLayerId=13e05ce7-d3db-41a0-80ae-d688f81dd017&mode=design)
> 
> It's unlikely it'd happen but it'd also be somewhat strange to access another user's alpha page by changing the `user_id` parameter (whereas on the beta page, i could have multiple friends who are referring me to join DS)

Gotcha, ok that makes good sense! We'd just be sending them their own share link directly!

**Pull request merged**
