### PR TITLE
Add more helpful alt tags to the Images Block.

### PR DESCRIPTION
**Pull request by DFurnes**
### What does this PR do?

This PR adds better* alt tags to Images Blocks loaded via GraphQL, for use by screen readers:

```html
<ul>
  <li><img alt="Woman crossing a sidewalk." src="https://images.ctfassets.net/81iqaqpfd8fy/4rvdH8Yik02wkigooaUeyQ/456d32b3ac1a3cc5df5e535e8dba4a0e/Walking.jpg?w=500&amp;h=500&amp;fit=FILL&amp;f=faces" /></li>
  <li><img alt="A man standing next to a bike." src="https://images.ctfassets.net/81iqaqpfd8fy/1kyUlGhOMkGmaGGOOaGIiY/1985a6ea9817312ae10be062789aa636/Riding_a_Bike.jpg?w=500&amp;h=500&amp;fit=FILL&amp;f=faces" /></li>
  <li><img alt="A passenger in a car using a smartphone." src="https://images.ctfassets.net/81iqaqpfd8fy/2sKIWp8tneaIOA6SyW0maI/ec64972f454b2ea66af246dda7966be3/Passenger.jpg?w=500&amp;h=500&amp;fit=FILL&amp;f=faces" /></li>
</ul>
```

### Any background context you want to provide?

Well, it's _theoretically_ a lot better. Unfortunately, we haven't filled out the `description` field for any of our uploaded media, so this currently does nothing. We should add that step to our editor guide (and briefly explain why it's important for accessibility).

I considered using the asset `title` instead, but looking at some examples (like `t-chick-mcclure-609632-unsplash` or `nfl food guide-01`) doesn't really inspire confidence... 🤦‍♂️

### What are the relevant tickets/cards?

Based on @mendelB's suggestion in #1319!

### Checklist

* [ ] Documentation added for new features/changed endpoints.
* [ ] Added appropriate feature/unit tests.
* [ ] Added screenshot to PR description of related front-end updates on **small** screens.
* [ ] Added screenshot to PR description of related front-end updates on **medium** screens.
* [ ] Added screenshot to PR description of related front-end updates on **large** screens.

### CODE REVIEW

**Comment by DFurnes** [comment]
Haha yeah, I can try to dig into that. I was just being lazy. 😅

**Comment by mendelB** [comment]
> Well, it's theoretically a lot better. Unfortunately, we haven't filled out the description field for any of our uploaded media, so this currently does nothing. We should add that step to our editor guide (and briefly explain why it's important for accessibility).

I'll add that to the running documentation ticket.
I also wonder if there's a way to require that field on Contentful 🤔

**Comment by mendelB** [comment]
> Haha yeah, I can try to dig into that. I was just being lazy. 😅

the saddest thing ever smh

**Comment by DFurnes** [comment]
@mendelB Added support to the PHP entity in 68d62a2 and confirmed they're showing up on the gallery at the end of the "Test Teens for Jeans" action page. 👁‍🗨

**Pull request merged**
