### PR TITLE
Adding voter registration action modal with static content

### PR DESCRIPTION
**Pull request by mendelB**
### What does this PR do?
This PR adds a `VoterRegistrationModal` component (along with the proper container, exports, and ModalSwitch `case`).

### Any background context you want to provide?
The modal is hardcoded with static content since [we've decided](https://dosomething.slack.com/archives/C3ASB4204/p1520279950000760) on showing this same modal across all campaigns that are feature-flagged for it to appear.

The actual rendering of this modal under some `TrafficDistribution` and feature flagging will be upcoming pending approval of the ModalLauncher changes #730 

image

### What are the relevant tickets/cards?
Pivotal ID [#155551810](https://www.pivotaltracker.com/story/show/155551810)

### CODE REVIEW

**Comment by lkpttn** [comment]
Is this a screenshot from the site? We have double Xs to close the modal here.

**Comment by mendelB** [comment]
It's from my local dev, I'm not sure why some modals still have that top-level X. Looking into it

**Comment by mendelB** [comment]
It is no longer! We just had to specify hiding it. I think this was to support modals with no card X ability which may no longer be the case.

**Comment by lkpttn** [comment]
Yeah, all modals should be presented in the carded fashion, so we can look at removing that extra code.

**Comment by mendelB** [comment]
Rebased from master to resolve merge conflicts but no new changes so gonna 🚢!

**Pull request merged**
