### PR TITLE
Cleaning up content page and hiding CTA for closed state

### PR DESCRIPTION
**Pull request by itsjoekent**
### What does this PR do?
- Removes unused code from ContentPage
- Restructures component files
- Hides the CTA on closed state

screen shot 2017-07-14 at 11 12 02 am

### CODE REVIEW

**Comment by deadlybutter** [comment]
Rebased @weerd

**Comment by deadlybutter** [comment]
So for some reason, the linter is failing in Wercker but not locally on this branch. Great!

**Comment by weerd** [comment]
Did you confirm by manually running `npm run lint -s`?

**Comment by weerd** [comment]
Sometimes the task watching for lint errors doesn't catch everything (or get triggered to run) from my experience. So before a PR push I try and remember to do a manual run 😄

**Comment by deadlybutter** [comment]
Yeah, it's fine for me

screen shot 2017-08-10 at 2 40 30 pm

**Comment by weerd** [comment]
Oh duh! I forgot I had this exact problem. You need to update npm. ESLint config got an updated version of eslint. If you update and then run the linter, your terminal will blow up w/ those same errors ;)

**Comment by deadlybutter** [comment]
I'm on npm 5.3.0 which seems to be the latest

**Comment by deadlybutter** [comment]
wait nvr mind

**Comment by deadlybutter** [comment]
yeah it is the latest, that aint it

**Comment by deadlybutter** [comment]
also ran an `npm install` to make sure that wasn't it...

**Comment by mendelB** [comment]
@itsjoekent What are the implications of the whole restructuring of `App.js` and `Page` that @weerd did on these changes? (also causing merge conflicts now)

**Comment by itsjoekent** [comment]
I just fixed the merge conflicts and got distracted -- and oh yeah this is too old haha

**Comment by weerd** [comment]
Still has merge conflicts. Maybe close this one and do the updates in a diff PR?

**Pull request closed without merging**
