### PR TITLE
Adding Snowplow GA plugin to mirror events to QA Fivetran Snowplow.

### PR DESCRIPTION
**Pull request by sheyd**
### What does this PR do?

This PR updates Google Analytics script code to include Snowplow Plugin. Currently Snowplow endpoint provided is for Quasar QA data warehouse.

### Any background context you want to provide?
We're experimenting with event capture into Snowplow by mirroring Google Analytics events to see what fidelity of data we capture into the Quasar platform.

The plan is to deploy this to https://qa.dosomething.org and test functionality to ensure it doesn't break anything. 

@mendelB @weerd Ideally we'd want to variablize the [endpoint](https://github.com/DoSomething/phoenix-next/compare/snowplow-ga-plugin?expand=1#diff-eecc5922a16f521021c82db256df300bR8) so we can swap out Quasar QA or Prod Snowplow collector endpoints per environment, correct? 

Installation documentation for the plugin is [here](https://github.com/snowplow-incubator/snowplow-google-analytics-plugin).

### What are the relevant tickets/cards?

Refs [Pivotal ID # 165642556](https://www.pivotaltracker.com/story/show/165642556)

### Checklist

* [ ] Documentation added for new features/changed endpoints.
* [ ] Added appropriate feature/unit tests.
* [ ] Added screenshot to PR description of related front-end updates on **small** screens.
* [ ] Added screenshot to PR description of related front-end updates on **medium** screens.
* [ ] Added screenshot to PR description of related front-end updates on **large** screens.

### CODE REVIEW

**Comment by sheyd** [comment]
@weerd @mendelB I went ahead and variablized the Snowplow URL.

**Comment by weerd** [comment]
I was contemplating moving the Snowplow script into a separate include file, but based on their docs and how they recommend inserting it, my initial review makes less sense.

**Comment by sheyd** [comment]
Thank you @weerd for the conditional logic additions here!!

**Comment by weerd** [comment]
@sheyd you're gonna need to rebase with `master` so that it fixes the StyleCI flag it's angry about!

**Comment by weerd** [comment]
Did you rebase from master @sheyd?? Check the changed files section. It's pulling in changes that already happened... 

Did you pull down master before rebasing?

**Comment by sheyd** [comment]
Closing in deference of [this PR](https://github.com/DoSomething/phoenix-next/pull/1415), since the rebase here added a bunch of files.

**Pull request closed without merging**
