### PR TITLE
Convert SignupButton into a plain ol' component.

### PR DESCRIPTION
**Pull request by DFurnes**
### What does this PR do?
This pull request refactors the somewhat hairy `SignupButtonFactory` into plain ol... `SignupButton`. Along the way, I continued to pull things that are scattered amongst a bunch of different containers closer to the where they're actually used.

So instead of…

```jsx
import SignupButtonFactory from '../SignupButton';

const SignupButton = SignupButtonFactory(({ clickedSignUp }) => (
    <Button onClick={() => clickedSignUp(legacyCampaignId || campaignId)} text={actionText} />
), 'call to action', { text: actionText });

return <div>{ isSignedUp ? null : <SignupButton /> }</div>;
```

…it's just:

```jsx
import SignupButton from '../SignupButton';

return <div>{ isSignedUp ? null : <SignupButton source="call to action" /> }</div>;

```

Ahhhhh. 😌

### Any background context you want to provide?
I tried my best to make sure this works the same everywhere, but would love some additional eyes to make sure I haven't broken anything unintentionally. ~In particular, I removed the ability to customize `actionText` case-by-case because it doesn't seem we're actually doing that anywhere.~ Re-added for the heck of it in 8cc784e.

### What are the relevant tickets/cards?
[#155625023](https://www.pivotaltracker.com/story/show/155625023)

### Checklist
- [ ] Documentation added for new features/changed endpoints.
- [ ] Added appropriate feature/unit tests.
- [ ] Added screenshot to PR description of related front-end updates on **small** screens.
- [ ] Added screenshot to PR description of related front-end updates on **medium** screens.
- [ ] Added screenshot to PR description of related front-end updates on **large** screens.

### CODE REVIEW

**Comment by weerd** [comment]
@DFurnes will this affect how it does converting an experiment? My upcoming PR (cleaning it up to push up in a couple min) for the Sixpack A/B `ledeBanner` experiment works with it 😬

**Comment by DFurnes** [comment]
Shouldn't! Everything should functionally work the same way.

**Comment by weerd** [comment]
@DFurnes I'll wait till you merge this before I push my PR up so I can have this in and test it 💃

**Comment by mendelB** [comment]
First of all OMG!
Second of all LMAO:
image

**Comment by DFurnes** [comment]
😉

**Pull request merged**
