### PR TITLE
Link action Docs & Contentful script update

### PR DESCRIPTION
**Pull request by mendelB**
### What's this PR do?

This pull request generates a Contentful migration script for the Link Action which contains some helper text updated (outlined in the Pivotal ticket), and some documentation.

### How should this be reviewed?
👁️ 

### Any background context you want to provide?
#2516 - making it clear to editors that the Link Action now functions solely as a Card + Button block and no longer as an embed renderer.

### Relevant tickets

References [Pivotal #175380207](https://www.pivotaltracker.com/story/show/175380207).

### Checklist

- [x] This PR has been added to the relevant Pivotal card.
- [x] Documentation added for new features/changed endpoints.
- [ ] Added screenshots of front-end changes on small, medium, and large screens.
- [ ] Added appropriate feature/unit tests.

### CODE REVIEW

**Review by lindsayrmaher — COMMENTED** [review]
LinkAction isn't a new content type right? Curious why the migration re built the entire link action file rather than just updating the changes portions

**Comment by mendelB** [comment]
> LinkAction isn't a new content type right? Curious why the migration re built the entire link action file rather than just updating the changes portions

@lindsayrmaher That's a good question! We must have never generated the migration for the Link Action when we evolved over to the new system of maintaining a single migration script per content type. This did remind me to delete the legacy individual migration scripts for the Link Action in https://github.com/DoSomething/phoenix-next/pull/2517/commits/6311501909f5c85b1f7d958967347057c400d397

**Review by lindsayrmaher — APPROVED** [review]
looking good, looks like some cypress tests might need to get re run?

**Comment by mendelB** [comment]
> looking good, looks like some cypress tests might need to get re run?

Looks like those flakey tests have struck again 😖 re-running the build!

**Pull request merged**
