### PR TITLE
(NOT 100% TESTED DONT MERGE) Queue refactor

### PR DESCRIPTION
**Pull request by itsjoekent**
### What does this PR do?
- Cut out a some extra stuff from the events we're not going to use, makes the code a bit nicer
- Added different types of auth events (Generic & Facebook)
- Added example Facebook signup action (Not used anywhere yet)

### Any background context you want to provide?
We want to run experiments that let people authenticate via Facebook with a 1 click experience. This work allows us to run these experiments. 

For example in the Quiz action,

```
export function quizConvert(quizId) {
  return ((dispatch, getState) => {
    // If the user is not logged in, handle this action later.
    if (! getState().user.id) {
      const quizData = getState().quiz[quizId];
      set(quizId, QUIZ_STORAGE_KEY, quizData.questions);

      return dispatch(queueFacebookAuthEvent('quizConvert', quizId));
    }
```

Note the last return!

### CODE REVIEW

**Comment by weerd** [comment]
Does this work allow for running the experiments or for recording the data behind the events related to 1-click auth?

**Comment by deadlybutter** [comment]
That reminds me, technically I should update the action array so these two are being watched. As for experiments, yes! See the PR for an example with the quiz

**Comment by weerd** [comment]
@itsjoekent also this one... can we close it?

**Comment by weerd** [comment]
Closing since PR is stale and has merge conflicts.

**Pull request closed without merging**
