### PR TITLE
Remove legacy Referrals code: Part 1

### PR DESCRIPTION
**Pull request by aaronschachter**
### What does this PR do?

This PR removes the Referrals db table, controller, and related code from a year ago that we no longer use. The routes for this code were removed in #1521. I've sanity checked that creating a photo post still works, as well as expected admin dashboard functionalityl.

Part 2 is not necessary to merge this, and would be a little bit more destructive. From what I can tell, the last remaining steps to remove would be to run migrations:

* Contentful migration to delete the `referralSubmissionAction` content type
* DB migration to drop the `referrals` table

### Any background context you want to provide?

As we begin building out this v2 Refer A Friend (started in #1521) and onboard new engineers to the project, it'd be ideal to get rid of stale code with conflicting/confusing namespace.

Plus, what better way to get to know a project than to trash 442 lines of code you didn't write?

### What are the relevant tickets/cards?

https://www.pivotaltracker.com/story/show/167655423

### Checklist

* [ ] Documentation added for new features/changed endpoints.
* [ ] Added appropriate feature/unit tests.
* [ ] Added screenshot to PR description of related front-end updates on **small** screens.
* [ ] Added screenshot to PR description of related front-end updates on **medium** screens.
* [ ] Added screenshot to PR description of related front-end updates on **large** screens.

### CODE REVIEW

**Comment by weerd** [comment]
> Plus, what better way to get to know a project than to trash 442 lines of code you didn't write?

😂

**Comment by weerd** [comment]
I think we may want to check Contentful (master) and see if `referralSubmissionAction` is being used on any campaigns etc and remove their use otherwise this might cause some trouble when trying to render the page.

**Comment by weerd** [comment]
Looks like on Contentful (master) there's 2 in use on published campaigns and 1 in draft which can probs be deleted. 1 of the published ones is not linked to a campaign and can be deleted and the other is linked to a now closed campaign. We can probs unlink the one connected to the closed campaign and delete the instance.

**Comment by aaronschachter** [comment]
Ok, going to remove the [Team Up Dream Up 2018 Referral Reportback](https://app.contentful.com/spaces/81iqaqpfd8fy/entries/59Hy58Z41q6kS8gISWocME) entry from [Team Up Dream Up  2018 Action Page](https://app.contentful.com/spaces/81iqaqpfd8fy/entries/59Hy58Z41q6kS8gISWocME), and save -- then delete the two  `referralSubmissionAction` entries?

**Comment by aaronschachter** [comment]
Oh wait, that's the one in draft. I only see two `referralSubmissionAction` entries in Contentful master - the one I linked to above, and then this one [Lose Your Vcard June Email Share](https://app.contentful.com/spaces/81iqaqpfd8fy/entries/2jFrjrJ0RuUcYmO6Y86aGe), not linked to anything.

**Comment by weerd** [comment]
The one in "draft" is from December of 2018 and not linked to anything. I think it's save to remove :) Yeah, just unlink the linked one, remove from Action Page and delete all the instances.

**Comment by aaronschachter** [comment]
Done!
Screen Shot 2019-08-02 at 10 18 07 AM

**Comment by aaronschachter** [comment]
>  delete the migration for this content type (https://git.io/fjHNA) and delete the content types via the Contentful GUI

Ok! Will do

>  confirm that we want to get rid of this feature entirely

I think that's a yes per the last section in the [tech spec](https://docs.google.com/document/d/1hzw8eBNLTwFFG2KQFdEHdljJbDpgW1awjG3wYjy_A_Q/edit) -- and agreed we could reference (or potentially revert) this PR to revitalize with a non-conflicting name should we ever need to.

**Comment by aaronschachter** [comment]
@mjain-1 - Just wanted to ping you on this work so you're aware. It removes the CSV export feature of the `referrals` SQL table in the Phoenix DB. This was used for when users were prompted enter their friends' email addresses (one campaign I know it was used for was Team Up Dream Up 2018) -- admins would download CSV and then manually send through Customer.io (more details in the [Product Brief](https://docs.google.com/document/u/1/d/1T0X1qltOwmG0gpRUPUNffOHFqZaRwOt1YIAT5GyyS_c/edit?usp=sharing)).

The last step for cleanup in this repo is to drop the `referrals` table completely. I'd imagine we don't need to keep this, as the data was manually imported through Customer.io but just wanted to make sure we're all on the same page. cc @DFurnes

**Pull request merged**
