### PR TITLE
Use GraphQL to load embeds.

### PR DESCRIPTION
**Pull request by DFurnes**
### What does this PR do?

This pull request is a companion to DoSomething/graphql#78. It updates our `Embed` component to fetch embeds via GraphQL – allowing us to fetch multiple embeds at once on content pages, and taking often long-running requests out of Phoenix's limited static resources.

### Any background context you want to provide?

Here are some examples of embeds happily rendering via GraphQL. Follow the links to test!

I've tested this with a [YouTube video](https://dosomething-phoenix-de-pr-1314.herokuapp.com/us/blocks/6HDADkeXfztKuAixfykEOD), [weird YouTube video](https://dosomething-phoenix-de-pr-1314.herokuapp.com/us/blocks/5ab09theBUskKoWgyiiIqS) (also doesn't fully embed on production… perhaps due to copyright?), and [a content site embed](https://dosomething-phoenix-de-pr-1314.herokuapp.com/us/blocks/4JTctxzTuwMy8ymAckEmA2). Finally, check out the old [Sincerely Us community page](https://dosomething-phoenix-de-pr-1314.herokuapp.com/us/campaigns/sincerely-us/community), where we load all ten embeds in one ~400ms HTTP request.

5iw9S9Dt4W4cou2c0qqmWq

5ab09theBUskKoWgyiiIqS

4JTctxzTuwMy8ymAckEmA2

### What are the relevant tickets/cards?

[#164637092](https://www.pivotaltracker.com/story/show/164637092)

### Checklist

* [ ] Documentation added for new features/changed endpoints.
* [ ] Added appropriate feature/unit tests.
* [ ] Added screenshot to PR description of related front-end updates on **small** screens.
* [ ] Added screenshot to PR description of related front-end updates on **medium** screens.
* [ ] Added screenshot to PR description of related front-end updates on **large** screens.

### CODE REVIEW

**Comment by weerd** [comment]
ooooooo 👀

**Comment by mendelB** [comment]
@DFurnes quick flag re the use of the embed API in the `IframPreview` for mobile
https://github.com/DoSomething/phoenix-next/blob/a1bd626f33e4feb24a0ccd50a4fb52c919e2393c/resources/assets/components/utilities/Iframe.js#L24

**Comment by DFurnes** [comment]
Oh indeed! I'll swap that to use this GraphQL query as well.

**Comment by DFurnes** [comment]
Fixed that up in 32f780b, and verified that the [Story Page Test](https://dosomething-phoenix-de-pr-1314.herokuapp.com/us/stories/page-test) renders as expected once again! (I also confirmed that there aren't any other `next/embed` calls lurking around with a search.)

Thanks for flagging that @mendelB! 🙇

**Comment by weerd** [comment]
> Finally, check out the old Sincerely Us community page, where we load all ten embeds in one ~400ms HTTP request.

🤯

**Comment by DFurnes** [comment]
Quick rebase to clear up that merge conflict! No other changes.

**Pull request merged**
