### PR TITLE
[#154734388] adding some styling edits

### PR DESCRIPTION
**Pull request by mendelB**
## _PULL REQUEST OVERVIEW_
Some super quick edits to the styling of the Section Header

image

https://dosomething.slack.com/archives/C2BPA7M8F/p1517863001000435?thread_ts=1517858302.000753&cid=C2BPA7M8F
[#154734388](https://www.pivotaltracker.com/story/show/154734388)

### CODE REVIEW

**Comment by weerd** [comment]
Thoughts on also using `margin-bottom: 48px`, so `$section-spacing on `.action-steps`? They feel a little more compacted now @lkpttn

screen shot 2018-02-05 at 6 06 59 pm

**Comment by lkpttn** [comment]
@weerd Agreed, we should add more space in between the actions. The new headers leave them looking a little samey, so I'd like to use space to distinguish them a bit.

**Comment by mendelB** [comment]
Should we be waiting on adding more space beneath the `action-step` till we have the individual actions (Eg. social share, voter reg) embedded within the action step as opposed to existing independently on the action page?

(Meaning, adding this space as of now would sometimes create a gap between the step and the action, as opposed to between the steps themselves:)
image


instead of:

image

**Comment by lkpttn** [comment]
^ I would say this isn't good but I can see where the complications are coming from. Would it be easier to think of it as space before any given step header?

**Comment by mendelB** [comment]
That definitely would be easier. We can throw in `24px` of `margin-top` for a combined `48`?

**Comment by weerd** [comment]
Nope! Don't mix margin top and bottom for this. For one thing, margins collapse, so if you make a top margin 24px and bottom margin 24px, the result is 24px.

**Comment by weerd** [comment]
We've defined everything with margin-bottom and switching to use both top and bottom is going to cause complication elsewhere. I think we should maybe set it to an inbetween value for now (36px) and do another dedicated pass on these in the future.

**Comment by mendelB** [comment]
Yeesh collapsing margins don't sound good. Ok I like that compromise. I think once we formalize this Actions Section > actions business it'll be way more straightforward with just a desired `margin-bottom`

**Comment by weerd** [comment]
Yeah, defs. Lets wait to re-address this once we move to all actions being isolated components and "action steps" _just_ being blocks that _contain_ actions!

**Pull request merged**
