### PR TITLE
Update to persist query params on campaign urls.

### PR DESCRIPTION
**Pull request by weerd**
### What does this PR do?

This PR fixes an issue where query parameters in URLs to campaign would be lost when redirecting the campaign to the `/action` page (there is a separate issue to address this behavior and eventually remove it). This update fixes the issue by passing along the `location.search` query params as a prop in the `Redirect` ReactRouter component.

### Any background context you want to provide?

Initially approached this by setting up a new helper function to handle relative URLs with query params (our `makeUrl()` helper only works well with absolute URLs), but then @mendelB and his very inquisitive mind found that the ReactRouter Redirect component can have a `search` prop passed to it to append query params in a string. Made the whole thing a lot easier.

This also cleans up the doc block in the `makeURL()` helper function.

### What are the relevant tickets/cards?

Refs [Pivotal ID #165323440](https://www.pivotaltracker.com/story/show/165323440)

### Checklist

* [ ] Documentation added for new features/changed endpoints.
* [ ] Added appropriate feature/unit tests.

### CODE REVIEW

**Comment by mendelB** [comment]
@weerd What's with the package.lock changes - is that just npm versions being different?

**Comment by mendelB** [comment]
> @mendelB and his very inquisitive mind

gif

**Comment by weerd** [comment]
> @weerd What's with the package.lock changes - is that just npm versions being different?

oh yeah, dang. I keep doing that with my iMac. It was missing some package, so needed to `npm install`

**Comment by weerd** [comment]
Removed the `package-lock.json` changes!

**Pull request merged**
