### PR TITLE
Update help message for # of affiliates supported

### PR DESCRIPTION
**Pull request by mirie**
Change the help message from #team-product to #help-product

### CODE REVIEW

**Comment by mirie** [comment]
It doesn't look like I have the permission to re-run the failed tests on CircleCI -- however the test failure seems to have nothing to do with this change: 

> Beta Referral Page Visit beta referral page, with valid user and campaign ID set - Visit beta referral page, with valid user and campaign ID set
> CypressError: Timed out after waiting '10000ms' for your remote page to load.

**Comment by aaronschachter** [comment]
This is sadness, as we were hoping https://github.com/DoSomething/phoenix-next/pull/1932 would be the fix.. and I see your branch is up to date. I am re-running the workflow now to hopefully ✅

**Comment by aaronschachter** [comment]
Re-ran and still see the same failure. Looking at the screenshot of failed test https://dashboard.cypress.io/projects/ayzqmy/runs/2024/specs and I see that the page is loaded correctly, but there's a HelloBar at the bottom.  I wonder if that's the culprit that causes the timeouts? 

cypress-screenshot

**Comment by DFurnes** [comment]
Oh my god, HelloBar strikes _again!_

**Comment by aaronschachter** [comment]
Haha yup. In a separate branch I'm working on, I got a timeout for a different non-referral-page test... the screenshot also shows a HelloBar

cypress-screenshot (1)

**Comment by mirie** [comment]
Oh dear - well q: can I merge this change or do we need to figure out the cypress test?

**Comment by DFurnes** [comment]
@mirie Go ahead and merge!

**Comment by DFurnes** [comment]
(Just continuing this discussion here, but absolutely not merge blocking.)

It's interesting that HelloBar is loading at all on these Cypress tests... on my local, I get a "Hello Bar script is not initialized. http://phoenix.test must be https://dosomething.org." warning in the console and nothing pops up.

That said, the fact that it _is_ popping up makes me think that isn't the thing that's timing out, since I'd imagine if that third-party script was dragging it's feet then it wouldn't appear at all...

**Comment by DFurnes** [comment]
Ah ok – I tried it out with a plain old `php artisan serve` (on http://localhost:8000, like the tests) and HelloBar _does_ run there).

After a bunch of reloads to try to get one of my tests to time out, I ran into another potential culpit… [lorempixel.com](http://lorempixel.com)! I opened my web inspector a bit late when I noticed it finally timing out, but here's the tail end:

Screen Shot 2020-02-20 at 11 29 23 AM

**Comment by DFurnes** [comment]
And for what it's worth, the actual [lorempixel.com](http://lorempixel.com) is timing out when I try to visit it in my browser so that seems pretty damning. I'm going to push up a PR to switch [this](https://github.com/DoSomething/phoenix-next/blob/cb59f9ef4e5d68aa37e56a53f680f78f378e303f/cypress/fixtures/graphql.js#L54) out to something that doesn't rely on a third-party service being online.

**Comment by DFurnes** [comment]
Pushed up that fix in #1937 (and for what it's worth, the tests passed on their first try)!

**Pull request merged**
