### PR TITLE
total voter registration display

### PR DESCRIPTION
**Pull request by Dinnall**
Added another card component to display total voter registration.

### What's this PR do?
This pull request further progresses on the voter registration campaign.
Added total voter registration for campaign alphas.

### How should this be reviewed?
👀
...

### Any background context you want to provide?
One note, the component isn't complete. Currently, the number being displayed isn't accurate yet.
This is just the placeholder of a bigger ticket. Will circle back to once another thicket is complete to pull data from.
...

### Relevant tickets

References [Pivotal #171707739](https://www.pivotaltracker.com/story/show/171707739).

### Checklist

- [X ] This PR has been added to the relevant Pivotal card.

Screen Shot 2020-03-12 at 2 59 27 PM

### CODE REVIEW

**Comment by aaronschachter** [comment]
@mirie @Dinnall  I'm confused about [this comment](https://www.pivotaltracker.com/n/projects/2417735/stories/171707739), why we no longer need the feature flag. Is the plan to leave this PR open until the total registrations is ready to be displayed?

**Comment by mendelB** [comment]
> @mirie @Dinnall I'm confused about [this comment](https://www.pivotaltracker.com/n/projects/2417735/stories/171707739), why we no longer need the feature flag. Is the plan to leave this PR open until the total registrations is ready to be displayed?

I'd agree that we should wrap this in a feature flag until this is ready to launch!

Another note, as mentioned in the Groom -- Not that this is necessarily a blocking issue at all, but just to be actively aware, that we're coupling the 'Info Bar / Page view' functionality with voter registration (which tbf was the intent of the original feature!), but this would be a deprecation of its current context-agnostic workability for any campaign.

**Comment by lindsayrmaher** [comment]
Plus one to @aaronschachter and @mendelB on the feature flag convo! Also just a general q with voter reg PRs, I assume we are following the same procedures as the applications team and should review any PRs we get assigned even if they aren't something we're working on.

**Comment by mirie** [comment]
Hey there! Ah! I think we do need a feature flag! When I removed the feature flag information from the ticket, they were two separate components. I forgot to add it back in after the change to alter the existing component!

**Comment by katiecrane** [comment]
@lindsayrmaher as someone who has reviewed a decent number of (very digestible!) voter reg PRs, my understanding is that anyone is on the table to review PRs from any team, just like right now we review Platforms PRs and vice versa.

**Comment by Dinnall** [comment]
@aaronschachter @mendelB Can someone explain feature flagging? 

> @mirie @Dinnall I'm confused about [this comment](https://www.pivotaltracker.com/n/projects/2417735/stories/171707739), why we no longer need the feature flag. Is the plan to leave this PR open until the total registrations is ready to be displayed?

**Comment by mendelB** [comment]
@Dinnall you can follow along @lindsayrmaher's PR from today to see how to add a feature flag and wrap a feature in it! https://github.com/DoSomething/phoenix-next/pull/1974

Essentially you
- Add a new Feature Flag ENV variable to our [`config/features.php`](https://github.com/DoSomething/phoenix-next/blob/master/config/features.php#L1-L21)
- Add it locally to your .env field e.g. `DS_ENABLE_VOTER_REG_DRIVE_TOTAL=true`
- import the `featureFlag` helper from [`.../helpers/index.js`](https://github.com/DoSomething/phoenix-next/blob/master/resources/assets/helpers/index.js#L528-L537)
- Wrap the code in a ternary expression, e.g:
```js
         {featureFlag('voter_reg_drive_total') ? (
             <div className="p-3 voter-registrations">
                <span className="voter-registrations__text uppercase">
                  total voter registrations
                </span>
                <h1 className="voter-registrations__amount">
                  {shortenedLink ? this.state.count : '?'}
                </h1>
              </div>
         ) : null }
```
- Profit! 

You can totally do this in this PR, no need for a new one!

**Pull request closed without merging**
