### PR TITLE
Fix issue where we would fetch wrong ID column.

### PR DESCRIPTION
**Pull request by DFurnes**
#### Changes
Oh my _god_. This fixes the great "Chloe debacle" of 2017. References #207.

😩

### CODE REVIEW

**Comment by deadlybutter** [comment]
wow

**Comment by deadlybutter** [comment]
are we worried changing the primary key will break anything?

**Comment by weerd** [comment]
Why did nothing show up regarding this in the past though?

**Comment by DFurnes** [comment]
> are we worried changing the primary key will break anything?

It shouldn't! In most cases we were specifically asking for this column.

**Comment by DFurnes** [comment]
> Why did nothing show up regarding this in the past though?

Wrote up a little bit in the linked issue and we should definitely do a retrospective, but the gist is that it was trying to find a integer user `id` based on the string `northstar_id` (which was always `58f...`), and until we had 58 users it was always returning `null`.

As soon as any environment had 58 users (so, Friday afternoon 🙃) it would break in the same way.

**Comment by weerd** [comment]
Ah, one of those _fun_ 🐛s. I feel like something similar to this has happened to us before... Thanks MongoIDs! lol

**Pull request merged**
