### PR TITLE
money money money

### PR DESCRIPTION
**Pull request by deadlybutter**
screen shot 2017-05-26 at 10 15 29 am

### CODE REVIEW

**Comment by deadlybutter** [comment]
screen shot 2017-05-26 at 10 23 17 am

Werker had a build failure but doesn't appear to be us, merging away

**Comment by DFurnes** [comment]
In the future, can you retry the build when that happens? Otherwise we wouldn't see any lint or test errors until the code is merged into the dev branch.

**Comment by deadlybutter** [comment]
@DFurnes Sure! In this case I knew the linter already passed but will do in the future

**Comment by DFurnes** [comment]
Okay. For what it's worth, looks like builds on the dev branch [are broken now](https://app.wercker.com/dosomething/phoenix-next/runs/build/59283a6e858c60000144b0ad?step=59283a9e0138e50001933e29) too.

**Pull request merged**
