### PR TITLE
add PhotoSubmissionBlock to contenful entry

### PR DESCRIPTION
**Pull request by Dinnall**
### What's this PR do?

This pull request Widen grid for photo uploader on story pages.

### How should this be reviewed?
👍 
...

### Any background context you want to provide?

...

### Relevant tickets

References [Pivotal # 173152297](https://www.pivotaltracker.com/n/projects/2401401/stories/173152297).

### Checklist

- [ x ] This PR has been added to the relevant Pivotal card.
- [ x ] Added screenshots of front-end changes on small, medium, and large screens.
Screen Shot 2020-07-02 at 12 01 21 PM

### CODE REVIEW

**Comment by mendelB** [comment]
@Dinnall  One quick question -- how does this look for unauthenticated users where we display the auth button. I have a feeling that might not work well in the wide grid 🤔  (We may have to apply this custom class conditionally if the user is autheticated)

**Comment by Dinnall** [comment]
> @Dinnall One quick question -- how does this look for unauthenticated users where we display the auth button. I have a feeling that might not work well in the wide grid 🤔 (We may have to apply this custom class conditionally if the user is authenticated)

Currently, the uploader isn't visible unless you're an authenticated user, if you click the button to add a photo it redirects to the login page

**Comment by mendelB** [comment]
> > @Dinnall One quick question -- how does this look for unauthenticated users where we display the auth button. I have a feeling that might not work well in the wide grid 🤔 (We may have to apply this custom class conditionally if the user is authenticated)
> 
> Currently, the uploader isn't visible unless you're an authenticated user, if you click the button to add a photo it redirects to the login page

Ah so the button itself doesn't stretch across the wide grid?

**Comment by Dinnall** [comment]
> > > @Dinnall One quick question -- how does this look for unauthenticated users where we display the auth button. I have a feeling that might not work well in the wide grid 🤔 (We may have to apply this custom class conditionally if the user is authenticated)
> > 
> > 
> > Currently, the uploader isn't visible unless you're an authenticated user, if you click the button to add a photo it redirects to the login page
> 
> Ah so the button itself doesn't stretch across the wide grid?

There is a button, but the uploader itself isn't visible. Here is an image of the current logout state 
Screen Shot 2020-07-02 at 12 40 36 PM

**Comment by mendelB** [comment]
Ahh yeah ok I don't think we'd want that stretched out on the wide grid. I think what we can do is import the [`isAuthenticated` helper method](https://github.com/DoSomething/phoenix-next/blob/28ff4ce032b993c8b5849295c14e54b99e7f1a2a/resources/assets/helpers/auth.js#L76-L81), and only attach the `grid-wide` _if_ they're authenticated:
`PhotoSubmissionBlock: isAuthenticated() ? 'grid-wide' : 'grid-narrow'`

**Comment by Dinnall** [comment]
> isAuthenticated() ? 'grid-wide' : 'grid-narrow'

This definitely looks better. Added another commit to reflect this change
Screen Shot 2020-07-02 at 1 07 01 PM

**Pull request merged**
