### PR TITLE
SocialShareTray updates

### PR DESCRIPTION
**Pull request by aaronschachter**
### What's this PR do?

This pull request updates the `SocialShareTray` buttons per [designs](https://share.goabstract.com/b4844e49-9440-4066-a422-c3857b0c48e7) linked in Pivotal, removing the text and aligning them left (instead of center).

It also adds more descriptive alt text for each social media icon image, and refactors the styles to deprecate the scss file with Emotion `css`.

Screenshots:

* [small](https://user-images.githubusercontent.com/1236811/94178489-01d81a80-fe50-11ea-8fd8-dfefc52b09ad.png)
* [medium](https://user-images.githubusercontent.com/1236811/94178444-f4bb2b80-fe4f-11ea-8333-631fe12388ce.png)
* [large](https://user-images.githubusercontent.com/1236811/94178369-dce3a780-fe4f-11ea-84f1-81f899fd9e70.png)

### How should this be reviewed?

:eyes:

### Any background context you want to provide?

I'll be opening a separate PR or two to update the rest of the `VoterRegistrationDriveAction` in a separate PR, for easier reviewing.

### Relevant tickets

References [Pivotal #174806681](https://www.pivotaltracker.com/story/show/174806681).

### Checklist

- [x] This PR has been added to the relevant Pivotal card.
- [ ] Documentation added for new features/changed endpoints.
- [x] Added screenshots of front-end changes on small, medium, and large screens.
- [ ] Added appropriate feature/unit tests.

### CODE REVIEW

**Review by lindsayrmaher — APPROVED** [review]
looking good!

**Comment by mendelB** [comment]
@aaronschachter this is a fantastic refactor! Just wanted to confirm that we accounted for the `SocialShareTray` rendered on the 
- [StoryPage](https://github.com/DoSomething/phoenix-next/blob/master/resources/assets/components/pages/StoryPage/StoryPage.js#L53-L57)
- [GeneralPage](https://github.com/DoSomething/phoenix-next/blob/fc320d8b28abd734887b1efd817b985b533f6de0/resources/assets/components/pages/GeneralPage/GeneralPage.js#L95-L102)

**Comment by mendelB** [comment]
Hmm, I think we just need to account for allowing them to be centered on both pages!

image

image


image

image

**Comment by mendelB** [comment]
Adding a `text-center` class to the surrounding div in the respective pages seems to do the trick!

**Comment by aaronschachter** [comment]
Thanks @mendelB - I'll fix this up ASAP, should have thought to search for the `SocialShareTray` (didn't realize it appears in other places besides a `SocialDriveAction`)

**Pull request merged**
