### PR TITLE
Add Prettier for super-easy code formatting!

### PR DESCRIPTION
**Pull request by DFurnes**
### What does this PR do?
This pull request adds [Prettier](https://prettier.io) and our [updated ESLint config](https://github.com/DoSomething/eslint-config/releases/tag/v4.0.0) to Phoenix Next. I've been using Prettier on [our GraphQL gateway](https://github.com/DoSomething/graphql) and some personal projects and it's _just divine_.

### Any background context you want to provide?
I'd recommend installing [the editor plugin](https://prettier.io/docs/en/editors.html) so you get on-the-fly reformatting as you work, but if not the git hooks should take care of you!

### What are the relevant tickets/cards?
N/A

### Checklist
- [ ] Documentation added for new features/changed endpoints.
- [ ] Added appropriate feature/unit tests.
- [ ] Added screenshot to PR description of related front-end updates on **small** screens.
- [ ] Added screenshot to PR description of related front-end updates on **medium** screens.
- [ ] Added screenshot to PR description of related front-end updates on **large** screens.

### CODE REVIEW

**Comment by DFurnes** [comment]
I know, I know! But it's all just automated updates! 😁

I'd recommend checking things out commit-by-commit: installing Prettier & updating ESLint (47e6ee8), removing some unused defaultProps (b29a318), adding a git-hook to automatically format files on commit (f6fef54), and _finally_ skimming the big one (7cb9d6e).

**Comment by DFurnes** [comment]
Another note that might not be obvious at first - this will auto-format JavaScript, but also JSON, Markdown, GraphQL queries, and SCSS! And there's [support for PHP](https://github.com/prettier/plugin-php) in the works! 🔜 🐘

**Comment by DFurnes** [comment]
Rebased to get latest `master` branch formatted with b356e42!

**Comment by DFurnes** [comment]
Ok, looks good to me - going to merge so we can all start working off the same baseline!

**Comment by weerd** [comment]
Post-merge 👍

**Pull request merged**
