### PR TITLE
Collection Pages on Homepage Campaign Gallery

### PR DESCRIPTION
**Pull request by mendelB**
### What's this PR do?

This pull request adds the Collection Page to the list of supported nodes in the Homepage `campaigns` reference field per updates in https://github.com/DoSomething/graphql/pull/283 (blocking). We do this by simply adding the Collection Page as a valid reference in Contentful & a queries type in the `CampaignCard` GraphQL fragment.

- https://github.com/DoSomething/phoenix-next/commit/df0e0a47cf96110bfbabacec232402a6a510fce5 generally updates the migration script per `master` since it was outdated.
- https://github.com/DoSomething/phoenix-next/commit/6edcdcc66d41cdb6b41ada67e6790be14fccd8f2 retires the legacy `HomePage` component & feature flag and removes the new prefix from the new `NewHomePage` (I know).
- https://github.com/DoSomething/phoenix-next/commit/6778120f1e131b32071ef3d656a755495f09e464 retires the legacy `blocks` & `subTitle` fields relevant to the legacy HomePage.

### How should this be reviewed?
👀 commit-by-commit

### Any background context you want to provide?
See https://github.com/DoSomething/graphql/pull/283 for more context.

### Relevant tickets

References [Pivotal #173522205](https://www.pivotaltracker.com/story/show/173522205), [Pivotal #171962874](https://www.pivotaltracker.com/story/show/171962874)
### Checklist

- [x] This PR has been added to the relevant Pivotal card.
- [ ] Documentation added for new features/changed endpoints.
- [ ] Added screenshots of front-end changes on small, medium, and large screens.
- [ ] Added appropriate feature/unit tests.

image

### CODE REVIEW

**Comment by katiecrane** [comment]
> 6edcdcc retires the legacy HomePage component & feature flag and removes the new prefix from the new NewHomePage (I know).

😂 and also thank you for this cleanup!!

**Comment by katiecrane** [comment]
@mendelB looks good! just checking that in your screenshot, is that Fossil thing in the gallery a collection page?

**Comment by mendelB** [comment]
> @mendelB looks good! just checking that in your screenshot, is that Fossil thing in the gallery a collection page?

Oops yes! I should have pointed that out explicitly.

**Review by katiecrane — APPROVED** [review]
This looks good except that circleci is upset with you - let me know if I can help with getting it to cooperate!

**Comment by mendelB** [comment]
> This looks good except that circleci is upset with you - let me know if I can help with getting it to cooperate!

I think this is going to be failing pending pulling in the schema changes from the open https://github.com/DoSomething/graphql/pull/283 which we rely on in this work.

**Comment by katiecrane** [comment]
@mendelB oh right that makes sense! I can review that one in a bit if it's still pending

**Pull request merged**
