### PR TITLE
changing social share link to be modal instead of block

### PR DESCRIPTION
**Pull request by mendelB**
### What does this PR do?
- Changes the link generated by `makeShareLink` for `campaign` types, to be linking to the modal instead of the block. 
-  the facebook share button in `CampaignUpdate`s  and `CampaignUpdateBlock`s which make use of the `helpers#makeShareLink` to generate their social links, are now linking to modals as a result
- Another side effect of this is that the primary link atop a campaign update 
screen shot 2017-11-03 at 2 39 37 pm
(in both blocks and regular) now also link to the modal. (Since the link used is the same as the social link). (This was approved by Ashley/Adam).

### Any background context you want to provide?
Older `CampaignUpdateBlocks` don't render so nicely in modals yet as for now they're being returned plainly in a `Card`. I'll work on another pull request to support them in models.

### What are the relevant tickets/cards?
https://www.pivotaltracker.com/story/show/152351435

### Checklist
- [ ] Documentation added for new features/changed endpoints.
- [ ] Added appropriate feature/unit tests.

### CODE REVIEW

**Comment by itsjoekent** [comment]
Are we worried about this change from a product perspective, @lkpttn @ashleybaldwin ?

**Comment by ashleybaldwin** [comment]
I'm not necessarily concerned by making the "campaign update" text link out to the modal. I chatted with adam about it and from other conversations with the campaigns team, they like the modal more for making links and i think giving them the ability to make that link easily by clicking the campaign update is actually nice.

**Comment by mendelB** [comment]
Truth is though that clicking it wouldn't really give them the modal link since the URL changes back to the regular campaign URL almost instantaneously

**Comment by mendelB** [comment]
image

**Comment by ashleybaldwin** [comment]
right click > copy url for the win!!

**Comment by DFurnes** [comment]
Gah yeah, we really need to get modals to use standard routing. I do kinda think it might make more sense to ask the campaigns team to manually swap `pages` to `modals` in the URL when sharing for now so we don't send users to pages they can't link to.

**Comment by itsjoekent** [comment]
@DFurnes What do you mean by standard routing?

**Comment by DFurnes** [comment]
Modals should be a normal React Router route (where whatever we're seeing on the page is reflected in the URL in the address bar), not a "redirect" to a Redux state.

**Comment by itsjoekent** [comment]
That was intentional though so we could have "background" and not just a blank page behind the modal.

**Comment by DFurnes** [comment]
We can do that with a normal route too, though.

**Comment by itsjoekent** [comment]
True I guess you could still make the redux dispatch while also returning the template component?

**Comment by DFurnes** [comment]
I don't think it should use Redux for this at all – this is a page routing concern, not an application state concern. We should be able to do this by including a `<Route>` component directly in the modal container that only pops content in there when on this route (and then the rest of the page still renders to the campaign based on the route prefix).

Part of [the philosophy](https://reacttraining.com/react-router/web/guides/philosophy) behind React Router v4 is that you can throw your routes wherever they make sense in the application, not just in a central "routes" component. So it's totally reasonable to have the `Modal` component handle whether or not to show this modal, while the `CampaignPage` renders what displays behind the modal.

Let me know if you want to chat IRL to scope out this work for a future sprint.

**Pull request closed without merging**
