### PR TITLE
add analytics for sign up and complete sign up

### PR DESCRIPTION
**Pull request by Dinnall**
### What's this PR do?

This pull request add analytics events to 1-click signup on the scholarship page

### How should this be reviewed?
🛤️ 
...

### Any background context you want to provide?

...

### Relevant tickets

References [Pivotal #175155765](https://www.pivotaltracker.com/n/projects/2401401/stories/175155765).

### Checklist

- [ x ] This PR has been added to the relevant Pivotal card.
- [ ] Documentation added for new features/changed endpoints.
- [ ] Added screenshots of front-end changes on small, medium, and large screens.
- [ ] Added appropriate feature/unit tests.

### CODE REVIEW

**Review by mendelB — COMMENTED** [review]
I'm a little confused per the attached Pivotal story, I recall discussing updating these events following [Pivotal #173454908](https://www.pivotaltracker.com/story/show/173454908) since then we can differentiate between users who are signed up, or not signed up, or unauthenticated, and then track accordingly? (Since the signup button will function differently for all three cases).

[Here's](https://dosomething.slack.com/archives/C03T8SDJG/p1602164687017900?thread_ts=1602084898.011500&cid=C03T8SDJG) the relevant discussion in Slack. cc @ddonizeth @katiecrane

**Comment by Dinnall** [comment]
> I'm a little confused per the attached Pivotal story, I recall discussing updating these events following [Pivotal #173454908](https://www.pivotaltracker.com/story/show/173454908) since then we can differentiate between users who are signed up, or not signed up, or unauthenticated, and then track accordingly? (Since the signup button will function differently for all three cases).
> 
> [Here's](https://dosomething.slack.com/archives/C03T8SDJG/p1602164687017900?thread_ts=1602084898.011500&cid=C03T8SDJG) the relevant discussion in Slack. cc @ddonizeth @katiecrane

ah! so should I wait? I noticed the ticket you linked isn't assigned I can jump on that if resolving that issue makes more sense

cc: @katiecrane @ddonizeth

**Comment by katiecrane** [comment]
oh yeah great point @mendelB ! I just read through that slack thread again and it seems like we messed up the order of operations here, and that the ticket about changing the button if a user is already signed up should come first! @ddonizeth I have the same question as Michael, should he hop over to the other card instead?

**Comment by ddonizeth** [comment]
@Dinnall @katiecrane that makes perfect sense to start with [ Pivotal #173454908](https://www.pivotaltracker.com/n/projects/2401401/stories/173454908) first before dealing with the analytics ticket!!!

**Comment by DFurnes** [comment]
Removing my review request so that Slack stops bugging me to look at this. Feel free to re-assign me when we pick this work back up! 😃

**Pull request closed without merging**
