### PR TITLE
Prefix assets and Next-specific routes.

### PR DESCRIPTION
**Pull request by DFurnes**
#### Changes
This pull request prefixes our asset directory and API endpoints with `next/` so it'll be easy to access them when viewing the site through the `www.dosomething.org/...` strangler pass-thru, without having to add a specific routing rule for each Next-specific URL.

🕸

### CODE REVIEW

**Comment by DFurnes** [comment]
Waiting on confirmation that this'll work from the ops side, but should be ready for review.

**Comment by DFurnes** [comment]
I'm not sure what the ETA is, but this should be safe to merge in the meantime and then things should start working whenever the extra Fastly routing rule kicks in. Direct access on [next.dosomething.org](https://next.dosomething.org) is still a-okay. 👌

**Comment by deadlybutter** [comment]
@DFurnes Sorry took so long to look at this one, seems good!

**Comment by DFurnes** [comment]
[Unplanned Work: Fix app issues with new Fastly routing rules.](https://trello.com/c/WljXjHrz/507-unplanned-work-fix-app-issues-with-new-fastly-routing-rules)

**Pull request merged**
