### PR TITLE
Use Rogue's v3 endpoints to fill post gallery... with GraphQL!

### PR DESCRIPTION
**Pull request by DFurnes**
### What does this PR do?
This pull request hooks up the `PostGallery` component to Rogue's v3 endpoints, so that we can start showing text and other non-photo post types in the gallery.

After grappling with actions, reducers, and normalizers for the afternoon, I realized that updating our Redux store to use the new post structure & API responses was going to be hairier than I'd first thought... so I time-boxed myself to an hour at the end of the day to see if it'd be quicker with our [prototype GraphQL server](https://graphql-qa.dosomething.org). I think it was! 😁

### Any background context you want to provide?
We've talked about using GraphQL for a while now, but haven't taken the plunge in a client application yet. It gives some [really attractive benefits](https://graphql-qa.dosomething.org/docs/README.md) for more efficient querying - especially for an app like Phoenix, where it has lots of content coming from multiple different sources!

While this wasn't planned as part of the card, it seemed like a good opportunity for opportunistic refactoring since the alternative would have been a pretty extensive re-write of our Redux logic.

### What are the risks?
This could go wrong!! I'm pretty confident so far, but some risks that come to mind:

- We haven't used GraphQL in production yet, and don't know how it'll perform. I did some quick [load testing](https://gist.github.com/DFurnes/d3bb776641935fd22adae946e33fef16) on the preview instance, though, and it looks like it should hold up fine enough.
- In an ideal world, it'd be nice to be able to toggle back to the "legacy" implementation if we saw things going wrong. Since we need Rogue's v3 API for text posts, though, we're stuck with some sort of forced implementation change regardless.
- I'm leaving on vacation next week, so probably not the best time for a hand-off. Of course, the alternative would have been handing off a hairy ol' Redux re-write so that's not great either.

### What's needed to ~merge this~ finish this?
We need to figure out a few more things before this is at feature parity:

- [x] Pagination: the basics, so the "Load More" button works
- [ ] Pagination: "loading" states as we load more
- [ ] Pagination: hide "load more" button when we run out of pages
- [ ] Reactions: display them in the interface
- [ ] Reactions: create/destroy (either via a mutation query, or some other way to sync up changes)

### What are the relevant tickets/cards?
[#155944555](https://www.pivotaltracker.com/story/show/155944555)

(How did we vote this card as a 3?!)

### Checklist
- [ ] Documentation added for new features/changed endpoints.
- [ ] Added appropriate feature/unit tests.
- [ ] Added screenshot to PR description of related front-end updates on **small** screens.
- [ ] Added screenshot to PR description of related front-end updates on **medium** screens.
- [ ] Added screenshot to PR description of related front-end updates on **large** screens.

### CODE REVIEW

**Comment by weerd** [comment]
Sorta random, didn't we decide on `CampaignGallery` for the component and content type name?

**Comment by DFurnes** [comment]
Ah, yep! Was just working off the existing component to start. 😄

**Comment by weerd** [comment]
No worries! I know that's not the point of this PR, just wanted to confirm 😬

**Comment by DFurnes** [comment]
I've restored the original `PostGallery` so the legacy template continues working as expected. The new GraphQL-backed gallery (dubbed `CampaignGalleryBlock`) will only be used when a "Custom Block" with type `gallery` is placed.

For development, I've been testing against [this one](http://phoenix.test/us/campaigns/mirror-messages/blocks/2iaAzD8xOsoUEiUMcokw4m) on Mirror Messages, and [this one](http://phoenix.test/us/campaigns/test-teens-for-jeans#step-2iaAzD8xOsoUEiUMcokw4m) at the very bottom of the action page on Test Teens for Jeans.

This should be safe to deploy now 🤞 as we continue developing it!

By default, content will be loaded from the [preview GraphQL instance](http://graphql-preview.dosomething.org). We can set the `GRAPHQL_URL` environment variable to `https://graphql-preview.dosomething.org/graphql` to override that on production. And if you need to test changes to the GraphQL schema, it's as easy as flipping that switch to `http://localhost:3000/graphql` with a running [local GraphQL server](https://github.com/DoSomething/graphql).

**Comment by DFurnes** [comment]
This should be safe to deploy now 🤞 as we continue developing it!

By default, content will be loaded from the [preview GraphQL instance](http://graphql-preview.dosomething.org). We can set the `GRAPHQL_URL` environment variable to `https://graphql-preview.dosomething.org/graphql` to override that on production. And if you need to test changes to the GraphQL schema, it's as easy as flipping that switch to `http://localhost:3000/graphql` with a running [local GraphQL server](https://github.com/DoSomething/graphql).

**Comment by DFurnes** [comment]
Finally, some notes on the remaining work here, based on our hand-off earlier today –

💟 __Reactions:__ show them in the interface! This _should_ be good-to-go with the `reactions` and `reacted` fields on the `Post` schema. I had thought at first that Rogue's JSON response wasn't sending along reaction data.... but don't be fooled! We just have very few actual reactions. 😇

💌  __Reactions:__ ability to like/unlike posts! This could be a great excuse to try creating a [mutation query](http://graphql.org/learn/queries/#mutations) that returns an updated `Post` (in which case, we should see the UI automatically update). Otherwise, it's also probably safe to just handle this with local state for now - it's unlikely a single post would appear more than once on a page.

🔚 __Pagination:__ we need to keep track of when we run out of pages (e.g. once we get an empty response from a `fetchMore` query) & hide the "Load More" button so users know they're at the end.

📑 __Pagination:__ we probably want to toggle the "loading" state on the "Show More" button as we load more posts. This seems like it could be a [clean approach](https://www.apollographql.com/docs/react/recipes/recompose.html#loading-status) for that, and includes links to some documentation on that `networkStatus` field we talked over.

🎴 __Text Posts:__ Rogue sends along a `type` field (pending Monday deploy) that we can use to decide what kind of component to render! Text content should be under `media { text }`.

OKAY, VACATION TIME CYA! 👋

**Comment by DFurnes** [comment]
Alright, rebased against `master` to fix that merge conflict & updated the default GraphQL URL to `https://graphql-qa.dosomething.org/graphql`, following the changes in DoSomething/devops#389.

**Pull request merged**
