### PR TITLE
Extend Homepage Article Styles to the rest of the site

### PR DESCRIPTION
**Pull request by Dinnall**
### What's this PR do?

This pull request extends article card styles to the rest of the site.
replace PageGalleryItem with PageCard
### How should this be reviewed?

...

### Any background context you want to provide?

...

### Relevant tickets

References [Pivotal #174220430](https://www.pivotaltracker.com/n/projects/2401401/stories/174220430).

### Checklist

- [ X ] This PR has been added to the relevant Pivotal card.
- [ ] Documentation added for new features/changed endpoints.
- [ X ] Added screenshots of front-end changes on small, medium, and large screens.
- [ ] Added appropriate feature/unit tests.

New appearance :
Screen Shot 2020-10-21 at 3 15 03 PM

### CODE REVIEW

**Review by mendelB — APPROVED** [review]
This is looking great! 🤩

**Review by mendelB — COMMENTED** [review]
https://github.com/DoSomething/phoenix-next/blob/6455934b6f4f96020bb519723abff71692d814a7/resources/assets/components/blocks/GalleryBlock/GalleryBlock.js#L39-L41

for the `Page` specific part of the query, it'd be neat to do what we did for the `CampaignCard` and `ScholarshipCard` where we import and use the specific components fragment:
https://github.com/DoSomething/phoenix-next/blob/6455934b6f4f96020bb519723abff71692d814a7/resources/assets/components/blocks/GalleryBlock/GalleryBlock.js#L9-L14
https://github.com/DoSomething/phoenix-next/blob/6455934b6f4f96020bb519723abff71692d814a7/resources/assets/components/blocks/GalleryBlock/GalleryBlock.js#L42-L43

**Comment by Dinnall** [comment]
> https://github.com/DoSomething/phoenix-next/blob/6455934b6f4f96020bb519723abff71692d814a7/resources/assets/components/blocks/GalleryBlock/GalleryBlock.js#L39-L41
> 
> for the `Page` specific part of the query, it'd be neat to do what we did for the `CampaignCard` and `ScholarshipCard` where we import and use the specific components fragment:
> https://github.com/DoSomething/phoenix-next/blob/6455934b6f4f96020bb519723abff71692d814a7/resources/assets/components/blocks/GalleryBlock/GalleryBlock.js#L9-L14
> 
> 
> https://github.com/DoSomething/phoenix-next/blob/6455934b6f4f96020bb519723abff71692d814a7/resources/assets/components/blocks/GalleryBlock/GalleryBlock.js#L42-L43

ah - this makes sense. I went ahead and pushed the changes

**Review by mendelB — COMMENTED** [review]
Awesome 🙌 

We should be able to get rid of this part now
```js
... on Page {
        slug
      }
```
Since we're using the fragment!

**Comment by Dinnall** [comment]
> Awesome 🙌
> 
> We should be able to get rid of this part now
> 
> ```js
> ... on Page {
>         slug
>       }
> ```
> 
> Since we're using the fragment!

Good catch, done 😌

**Comment by mendelB** [comment]
@Dinnall sorry last thing -- can we delete the `PageGalleryItem` component now? (After confirming that it's not being used anywhere else, but I don't _think_ it would be!)

**Comment by Dinnall** [comment]
> @Dinnall sorry last thing -- can we delete the `PageGalleryItem` component now? (After confirming that it's not being used anywhere else, but I don't _think_ it would be!)

no worries lol, it was only being used in the `GalleryBlock.js`. I removed it

**Review by mendelB — APPROVED** [review]
👏

**Review by mendelB — APPROVED** [review]

**Pull request merged**
