### PR TITLE
Logging for Gateway Validation Exceptions

### PR DESCRIPTION
**Pull request by mendelB**
### What does this PR do?

This PR updates the reporting for Gateway validation errors.
- adds `Gateway ValidationException`s to the `$dontReport` list
- adds a debug level log for those exceptions instead

### Any background context you want to provide?
This was raised regarding an influx of these errors seeming to inflate our reported error count from Papertrail. 

One other difference in the logging I'd point out is that whereas the error log before had the id/email of the affected user, but obscured the actual message behind an object - e.g.
```
2019-01-07 15:13:40] local.ERROR: Exception from "POST v3/posts": [422] Validation errors returned. 
{"userId":"59b83901a0bfad2fd539736f","email":"mblesofsky@dosomething.org",
"exception":"[object] (DoSomething\\Gateway\\Exceptions\\ValidationException(code: 422): Exception from \"POST v3/posts\": [422] Validation errors returned. at /home/vagrant/Code/phoenix-next/app/Services/RogueClient.php:43)
```

This will now *not* show the id/email but show the error message - e.g.
```
[2019-01-07 15:13:40] local.DEBUG: Exception from "POST v3/posts": [422] Validation errors returned. {"file":["The file has invalid image dimensions."]} 
```

I wasn't sure how to add those details in there and whether we needed that info, or if we did - could tie the error to the [log of the users request](https://github.com/DoSomething/phoenix-next/blob/validation-logging/app/Http/Controllers/Api/CampaignPostsController.php#L64) via timestamp.

### What are the relevant tickets/cards?
https://dosomething.slack.com/archives/C3ASB4204/p1546401674002400

### CODE REVIEW

**Comment by weerd** [comment]
> I wasn't sure how to add those details in there and whether we needed that info, or if we did - could tie the error to the log of the users request via timestamp.

This might mean we end up doing something like Rogue did with a "transaction ID" that gets added for the life of a request cycle or something 🤔

**Comment by DFurnes** [comment]
> This might mean we end up doing something like Rogue did with a "transaction ID" that gets added for the life of a request cycle or something 🤔

These are actually added by Heroku's router (and then [forwarded to downstream requests by Gateway](https://github.com/DoSomething/gateway/blob/master/docs/traits/ForwardsTransactionIds.md))! We just need to add a little configuration in `AppServiceProvider` to [tell Monolog about them](https://github.com/DoSomething/rogue/blob/e767fe012d7318c44716e0fda37e6faafa7929db/app/Providers/AppServiceProvider.php#L31-L38).

**Comment by mendelB** [comment]
> > This might mean we end up doing something like Rogue did with a "transaction ID" that gets added for the life of a request cycle or something 🤔
> 
> These are actually added by Heroku's router (and then [forwarded to downstream requests by Gateway](https://github.com/DoSomething/gateway/blob/master/docs/traits/ForwardsTransactionIds.md))! We just need to add a little configuration in `AppServiceProvider` to [tell Monolog about them](https://github.com/DoSomething/rogue/blob/e767fe012d7318c44716e0fda37e6faafa7929db/app/Providers/AppServiceProvider.php#L31-L38).

Oh wayy dope! @weerd @DFurnes Is this something we indeed want to add in a follow-up PR?

**Comment by DFurnes** [comment]
Yeah, let's! I think it's super helpful to be able to see.

**Pull request merged**
