### PR TITLE
Sixpack base env

### PR DESCRIPTION
**Pull request by jocoso**
### What does this PR do?

The default environment after cloning phoenix-next shows env variable for SIXPACK_BASE_URL as https://experiments-qa.dosomething.org instead of https://experiments-qa.dosomething.org/api what causes the testing environment to constantly ask for authentication while SIXPACK_ENABLED is true. 

### Any background context you want to provide?

Screen Shot 2019-06-27 at 1 16 35 PM

### Checklist

* [ ] Documentation added for new features/changed endpoints.
* [ ] Added appropriate feature/unit tests.
* [ ] Added screenshot to PR description of related front-end updates on **small** screens.
* [x] Added screenshot to PR description of related front-end updates on **medium** screens.
* [ ] Added screenshot to PR description of related front-end updates on **large** screens.

### CODE REVIEW

**Comment by mendelB** [comment]
This is great, @jocoso!

This highlighted a few questions:
1. Is the `SIXPACK_BASE_URL` name a misnomer since it's got the `/api` route?
2. It seems that the `SIXPACK_ENABLED` env variable, even when set to `false` would still prompt this auth pop up -- is it actually controlling anything? We don't seem to be using it anywhere aside from passing it to the front-end https://github.com/DoSomething/phoenix-next/blob/b96abb3a0df3a61ee8caa05f54a9f5b8b8b34dac/app/Providers/AppServiceProvider.php#L36

**Comment by weerd** [comment]
> It seems that the SIXPACK_ENABLED env variable, even when set to false would still prompt this auth pop up -- is it actually controlling anything?

The auth pop up is not related to this at all.

I think we used to use it but after some of the rework last summer it got ignored. I did want to bring it back in and use it with some of my upcoming Sixpack work since I sometimes use a local Sixpack server and would be a nice way to just keep any Sixpack stuff from working if not enabled.

**Comment by mendelB** [comment]
> > It seems that the SIXPACK_ENABLED env variable, even when set to false would still prompt this auth pop up -- is it actually controlling anything?
> 
> The auth pop up is not related to this at all.
> 
> I think we used to use it but after some of the rework last summer it got ignored. I did want to bring it back in and use it with some of my upcoming Sixpack work since I sometimes use a local Sixpack server and would be a nice way to just keep any Sixpack stuff from working if not enabled.

Ah ok that makes sense!

**Comment by mendelB** [comment]
@jocoso Feel free to merge this Pull Request! 🎉

**Pull request merged**
